services:
  - type: worker
    name: ishi-music-bot
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: YOUTUBE_PREMIUM
        value: "false"
